packageExtensions:
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  typeorm@*:
    dependencies:
      sql.js: '*'
  typesense@*:
    dependencies:
      '@babel/runtime': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - .yarn/plugins/@monstrs/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
