plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/microservices': '*'
      '@grpc/proto-loader': '*'
      'grpc': '*'
  '@nestjs/mapped-types@*':
    peerDependencies:
      'class-transformer': '*'
  '@nestjs/typeorm@*':
    dependencies:
      'rxjs': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/microservices': '*'
      '@nestjs/websockets': '*'
      'reflect-metadata': '*'
      'rxjs': '*'
  '@nestjs/common@*':
    dependencies:
      '@nestjs/platform-express': '*'
      'class-transformer': '*'
      'class-validator': '*'
      'cache-manager': '*'
      'reflect-metadata': '*'
      '@grpc/proto-loader': '*'
      'grpc': '*'
      'rxjs': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      'reflect-metadata': '*'
      'grpc': '*'
      'rxjs': '*'
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@monstrs/mctl-ui@*':
    dependencies:
      '@monstrs/logger': '*'
