packageExtensions:
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/microservices@*':
     dependencies:
       grpc: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - .yarn/plugins/@monstrs/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-2.4.1.cjs
