enableGlobalCache: false

packageExtensions:
  '@smithy/middleware-retry@*':
    dependencies:
      '@smithy/node-config-provider': '*'
  '@smithy/config-resolver@*':
    dependencies:
      '@smithy/node-config-provider': '*'
  '@smithy/util-retry@*':
    dependencies:
      '@smithy/types': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/platform-express': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
  '@nestjs/testing@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/platform-express': '*'
  '@opentelemetry/core@*':
    dependencies:
      '@opentelemetry/api': '*'
  '@opentelemetry/sdk-logs@*':
    dependencies:
      '@opentelemetry/api': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-remote.cjs
