packageExtensions:
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@grpc/proto-loader': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@grpc/proto-loader': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  graphql-ws@*:
    dependencies:
      ws: '*'
  typeorm@*:
    dependencies:
      sql.js: '*'
      sqlite3: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230302.hash-20c60c4a.cjs
