packageExtensions:
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@monstrs/mctl-ui@*':
    dependencies:
      '@monstrs/logger': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/platform-express': '*'
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      grpc: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/mapped-types@*':
    peerDependencies:
      class-transformer: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      grpc: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/testing@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      grpc: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  'eslint-module-utils@*':
    dependencies:
      eslint-import-resolver-node: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
